apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: documind-backend-secrets
  namespace: documind
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: documind-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: documind-dev-backend-secrets
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: documind-dev-backend-secrets
        property: JWT_SECRET
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: documind-dev-backend-secrets
        property: GEMINI_API_KEY
