apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: documind-backend
  namespace: documind
spec:
  replicas: 2
  selector:
    matchLabels:
      app: documind-backend
  strategy:
    canary:
      steps:
        - setWeight: 25   # send 25% of traffic to the new version
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100  # full rollout
  template:
    metadata:
      labels:
        app: documind-backend
    spec:
      serviceAccountName: documind-backend
      containers:
        - name: backend
          image: 332130072211.dkr.ecr.us-east-1.amazonaws.com/documind-backend:5ead8377e8a0e1e7ae0e333a8ab008fac52048cb
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: documind-backend-secrets
          env:
            - name: AWS_S3_BUCKET_NAME
              value: "documind-dev-documents-332130072211"
            - name: AWS_REGION
              value: "us-east-1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10