apiVersion: v1
kind: Namespace
metadata:
  name: documind
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: documind-backend
  namespace: documind
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::560205084952:role/documind-dev-backend-role